package com.receipttracker.model;

public enum MaintenanceType {
    OIL_CHANGE,
    TIRE_ROTATION,
    TIRE_REPLACEMENT,
    AIR_FILTER,
    CABIN_FILTER,
    BRAKE_INSPECTION,
    BRAKE_PADS,
    BRAKE_ROTORS,
    TRANSMISSION_SERVICE,
    COOLANT_FLUSH,
    SPARK_PLUGS,
    BATTERY_REPLACEMENT,
    TIMING_BELT,
    TIMING_CHAIN,
    SERPENTINE_BELT,
    WHEEL_ALIGNMENT,
    FUEL_FILTER,
    WIPER_BLADES,
    INSPECTION_EMISSION,
    DETAILING,
    ACCIDENT_REPAIR,
    RECALL_SERVICE,
    OTHER
}
